### PR TITLE
feature/typedoc: ready for auto generate typescript documentation

### PR DESCRIPTION
**Pull request by RSginer**
I think this feature is very interesting for all libraries. I added a gulp task for generate typescript docs, i am using this on my library project:  https://ngbat.github.io/robin-ui/docs/

### CODE REVIEW

**Comment by jvandemo** [comment]
@RSginer &mdash; Thank you for you PR, much appreciated!

I really like the feature, but as mentioned in #70, we must think about how many people will use this feature vs the fact that it adds a lot of new dependencies, which makes `npm install` take longer when someone generates a new library.

If others are interested in having the feature, I am definitely open to adding it.

So I would suggest that others add a comment to this PR if they wish to have this included, so that we can merge this PR if there is enough interest.

Meanwhile, we could put up a wiki page with guidelines on how to generate docs using typedoc and gulp.

So if you could provide the guidelines in a written text, that would be awesome.

Thanks again for your efforts! 👍

**Comment by RSginer** [comment]
Maybe you want to create branch for this if is not instersting by default. Anyway i will create a guide in the wiki. Nice work!

**Comment by xxxtonixxx** [comment]
I think it is a main feature for a library. The most of libraries have and need docs 👍

**Comment by jdjuan** [comment]
I also agree. It can be a great plus for this generator if it has documentation out of the box

**Comment by RSginer** [comment]
I have been researching and maybe it is better to generate the documentation with [compodoc ](https://github.com/compodoc/compodoc)` I could implement it in the project if it is more interesting comment about it please

**Comment by jvandemo** [comment]
@RSginer &mdash; I had a look at both and I think compodoc is a better fit. The resulting documentation is more relevant since it is aimed at Angular code.

Do you want to create a PR for it or do you want me to add it?

Thanks again for your help! 👍

**Comment by jvandemo** [comment]
FYI, the command to run compodoc would be:

```bash
$ ./node_modules/.bin/compodoc src -p src/tsconfig.es5.json -s
```

**Comment by RSginer** [comment]
Thanks i want to send a PR :) Give me a day to prepare it and i can implement compodoc. Thanks again for the command

**Comment by jvandemo** [comment]
@RSginer &mdash; Awesome, if you need help, just shout 👍

**Comment by RSginer** [comment]
Closed in favor of #76

**Pull request closed without merging**
