### PR TITLE
feat(playground): Added a small playground based on systemjs

### PR DESCRIPTION
**Pull request by izifortune**
This feature enable to visualize changes of your
module without the needs to link the module to another
app.

### CODE REVIEW

**Comment by jvandemo** [comment]
@izifortune &mdash; This is awesome, thank you!

Would you be able to make the following changes:

- move all playground related files in the generator to `src/app/templates/playground`
- move all playground related files in the output library to `playground`

Currently, `index.html` and the SystemJS files are in the root of the library. It would be great if everything was in the same `playground` directory.

Can you also rebase on the latest version of this generator? Then we can merge your changes.

Thanks again, wonderful job!! 🏆

**Comment by izifortune** [comment]
@jvandemo I've managed to contain everything inside playground but there is a catch:

Currently lite-server will server everything from the root folder of the package, moving to have a baseDir of playground means that the `node_modules` and `dist` folder are not visible.

The only way that i've found to make this work is to use symlinks inside the playground.
Is this acceptable?

**Comment by jvandemo** [comment]
@izifortune &mdash; What if you run lite-server in the root and navigate your browser to `http://localhost:3000/playground/`? Would that allow playground to access `node_modules`?

Thanks again for your great work!

**Comment by izifortune** [comment]
Yes that will work but i'm not in a position to say which one is better. Your call 😄

**Comment by izifortune** [comment]
@jvandemo  rebased, fixed the linting errors and also managed to run from the root but serving only /playground/index.html as default.

This is done in the `bs-config.json` using routes i've configured the main route `/` to be `/playground`.

So no symlinks but at the same time `localhost:3000` will serve the index.html of the playground.

**Comment by matthewharwood** [comment]
Any update on this ?!

**Comment by jvandemo** [comment]
@izifortune &mdash; Awesome work, thank you so much! 👍  🏆

**Comment by pietromarrone** [comment]
While the library works well even exported and installed, the Playground cannot fin my dependency: 
`http://localhost:3000/ng2-webstorage 404 (Not Found)`
How anch where to configure it?

**Comment by revspringjake** [comment]
@pietromarrone -| I had the very same issue. If you look at the file path you are importing from it is probably missing the file extension, which we typically leave off as the loader will add it. If you notice your ng2-webstorage has no file extension. What worked for me was to add this to the systemjs.config.js

  packages: {
      ".": {
        defaultExtension: 'js'
      },
      app: {......

After I added this, the playground would load my files. The other fix is to just add the extension yourself to the file paths in your modules. I noted that worked for me as well.

I tried "playground" but only "." has worked so far.

Then I just added an NPM Link to the real package guts as mentioned above. Everything is working now for developing locally for me.

**Comment by jvandemo** [comment]
@izifortune &mdash; Would you be able to have a look at this? Thanks in advance!

**Comment by jvandemo** [comment]
Change has been implemented and released as v12.2.0.

Thank you for reporting, much appreciated! 👍

**Pull request merged**
