### PR TITLE
feat(jest): Add jest support

### PR DESCRIPTION
**Pull request by izifortune**
The benefits from switching from karma to jest are clear,
test execution speed its a huge factor. If you want to
have a read about it please follow
https://medium.com/aya-experience/testing-an-angularjs-app-with-jest-3029a613251.

### CODE REVIEW

**Comment by jvandemo** [comment]
@izifortune &mdash; Thank you, this is awesome!

Quick question: is it possible to keep karma and add jest support on top so we can have:

```
"test": "tsc && karma start"
"test-jest": "jest",
"test-jest:watch": "jest --watch",
"test-jest:ci": "jest --runInBand"
```

Alternatively, we could prompt the user to pick either Karma or Jest when running the generator.

What do you think? Thanks!

**Comment by izifortune** [comment]
@jvandemo sure thing I can do that

**Comment by jvandemo** [comment]
@izifortune &mdash; Thank you, looking forward to trying it out 👍

**Comment by izifortune** [comment]
Added jest as an option. I just noticed that at the moment there's no setup for karma yet

**Comment by jvandemo** [comment]
@izifortune &mdash; Great work! 👍 

There is indeed no configuration for Karma yet. Would you be interested in adding one? If not, I can also have a look at it. Thanks again for your wonderful effort!

**Comment by izifortune** [comment]
Can do that in another pr, one thing at the moment I'm using 2 package json
to have jest and karma do you think it's better to just have one? Less
things to maintain?

**Comment by charlouze** [comment]
When will this pr be merged ? I think having a way of testing the library out of the box is really a good thing.

**Comment by jvandemo** [comment]
@izifortune &mdash; I finally had a chance to test this. Great work!

Can you please rebase this PR on the latest version of master so we can merge your changes?

It's fine to have a separate `package.json` for jest in the generator source code. There is a substantial difference with the default `package.json` that may be easier to maintain by keeping them separate instead of inline template expressions.

Thanks again for your efforts! 👍

**Comment by izifortune** [comment]
@jvandemo  Rebased with current master.
Thank you for the time that you are putting into this!

**Comment by jvandemo** [comment]
@artemsky &mdash; PR has been merged and released as v11.0.0.

Thanks again for your wonderful contribution, much appreciated! 👍

**Pull request merged**
