### PR TITLE
feat(umd): add support to generate UMD bundle

### PR DESCRIPTION
**Pull request by jvandemo**
This PR adds the ability to generate a UMD bundle for the library.

A UMD bundle can be used in Node.js, with SystemJS or as a script tag (e.g. with Plunker, Fiddle, etc).

### CODE REVIEW

**Comment by jvandemo** [comment]
Looking for some testers to see if UMD bundle generation is working as expected.

@caroso1222, @jdjuan Would you be interested in testing this feature? Thanks in advance!

**Comment by jdjuan** [comment]
@jvandemo will do so tomorrow 💪. Thanks for this PR!

**Comment by jvandemo** [comment]
@jdjuan &mdash; Thank you, much appreciated! 👍

**Comment by jdjuan** [comment]
Hey @jvandemo really sorry for taking too long to test this 😅 I didn't quite know how to do it. I still don't. But I guess since you published you are fully sure it works, I will try to be faster next time 😅

**Comment by jvandemo** [comment]
@jdjuan &mdash; No problem at all, please don't apologize. I already appreciate a lot what you are doing to help this generator forward.

I had to merge early because people were waiting for this feature and I have a busy week so I won't always have the time to follow up before or after work.

Also, I'm suspecting it should behave fine on Windows and Linux as it uses the standard gulp plugins and nothing exotic was added.

If it doesn't, I'm sure people will take the effort to log issues.

Thanks again for your help and follow-up! 👍

**Pull request merged**
