### PR TITLE
feat(glup sass): add scss file build

### PR DESCRIPTION
**Pull request by deblockt**
add scss file build for inline template write with sass engine

### CODE REVIEW

**Comment by RSginer** [comment]
Nice feature i really like because im working in a Angular UI library and my components has scss but i don't now if this is really interesting for other types of library. Anyways nice work!

**Comment by jvandemo** [comment]
@deblockt &mdash; Thank you for the PR!

We have been hesitating to add SCSS support, as discussed here: https://github.com/jvandemo/generator-angular2-library/pull/65#issuecomment-295080651.

> There have been quite a bit of [issues with node-sass lately](https://github.com/sintaxi/harp/issues?utf8=%E2%9C%93&q=node-sass). I'm not sure if these issues would apply to this generator, but if they do, it may be wise for us to create a wiki page on how to include support for Sass, instead of adding the actual code.

> It would be a bummer if the generator was prevented from evolving because some third party support like Sass or Less does not cooperate as expected.

What are your thoughts? Thanks in advance!

**Comment by jdjuan** [comment]
@deblockt haven't chimed in yet, but I'd like to say something:
We want this generator to follow at least two principles: we want it to be **as lightweight as possible** and at the same time **we want it to be able to evolve** into something increasingly solid

In my opinion this PR allows those two principles since it works for both, `.css` and `.scss` files. 
If our users want to create a stable library they can use CSS, and if at some point they change their mind, then they can use SASS out-of-the-box (without further configuration!, which is cool).

At the very end is the user who decides what tool to use (with their pros and cons), we are just allowing them to choose.

FYI: @jvandemo @caroso1222

**Comment by deblockt** [comment]
i agree with @jdjuan, the only issues is that new dependency is downloaded on project installation. 
But it's not a issue because this is a dev dependency, it don't weigh down the builded library.

**Comment by jvandemo** [comment]
@deblockt &mdash; I have tried it locally and everything runs smoothly on MacOS.

@jdjuan &mdash; Thank you for jumping in.

Can anyone confirm whether this works as expected on Linux and Windows?

Thanks in advance!

**Comment by jdjuan** [comment]
I can confirm it works for Windows :+1:

**Comment by jvandemo** [comment]
@jdjuan &mdash; Thank you for the confirmation! 👍

**Comment by jvandemo** [comment]
Merged and released as v9.3.0.

@deblockt &mdash; Thank you for your contribution! 👍 
@jdjuan &mdash; Thank you for your input! 👍

**Pull request merged**
