### PR TITLE
Suggestion: package.json version auto-sync

### PR DESCRIPTION
**Pull request by btgoodwin**
In my workflow, I use `npm version ...` to bump versions, but this will not update the distributed `src/package.json` after a build (i.e., the one that is copied to `dist`).  So what this patch does is add trio of version scripts that first update the `src/package.json` with `./package.json`'s version and then add `src/package.json` to the staged commit.  NPM's `postversion` will then commit the tag with the synchronized `package.json` versions so that when I run `npm publish` in `dist`, the version is correct.

I hope this helps someone else. :-)

### CODE REVIEW

**Comment by manolof** [comment]
```bash
> sed -i -E 's/("version":[[:space:]]*").+(")/\1'$npm_package_version'\2/g' src/package.json

sed: 1: "s/("version":[[:space:] ...": \1 not defined in the RE
```

**Comment by btgoodwin** [comment]
It works on Linux for me but on macOS, it produces that error because of
the version of sed. You end up needing “-i .bak” rather than just “-i” and
then have another script to delete the backup file. I’ve been meaning to
amend this PR with that, but I’m out of the office.

**Comment by btgoodwin** [comment]
@manolof I've updated the PR with a pair of commits to work around some versions of `sed -i` requiring the creation of a backup file, and then a script for removing that backup file.

**Comment by manolof** [comment]
@btgoodwin thanks! In the meanwhile, i've also used [sync-json](https://www.npmjs.com/package/sync-json)

**Comment by btgoodwin** [comment]
Nice!  That is a much more robust and flexible solution.

**Comment by izifortune** [comment]
Running on OSX i got the following error:

```
 sed -i .bak -E 's/("version":[[:space:]]*").+(")/\1'$npm_package_version'\2/g' src/package.json

sed: -e expression #1, char 1: unknown command: `.'
```

I have one question regarding the modify src/package.json will it be included during in the same commit or will it stays as modified file?

**Comment by btgoodwin** [comment]
@izifortune, I think I should perhaps close this PR.  The `sync-json` route seems to be cleaner.  I haven't created a PR yet for my current configuration because I'm convinced it could use some other changes, like a user-defined file for what packages to synchronize.  

[Here](https://github.com/geontech/angular-redhawk) is a library I develop using this generator.  In my case, I use the `[npm version](https://github.com/Geontech/angular-redhawk/blob/master/package.json#L12)` command to synchronize the `package.json` when I'm getting ready to tag and release a version.  I then migrated all the `sync-json` logic from the `scripts` into `gulpfile.js`: [top level task](https://github.com/Geontech/angular-redhawk/blob/master/gulpfile.js#L164), [copy the newly-updated version](https://github.com/Geontech/angular-redhawk/blob/master/gulpfile.js#L171), [and sync a 'manifest' of things](https://github.com/Geontech/angular-redhawk/blob/master/gulpfile.js#L180).  It's that last step that I think could use some extra customization to make it more generic.

**Pull request closed without merging**
