### PR TITLE
Copy Root README to dist

### PR DESCRIPTION
**Pull request by dbfannin**
This PR copies the README.MD file at the root of the generated project to the /dist directory. 

The thought is that the user shouldn't have to maintain multiple README files. However, if you see value in there being a separate README for distributable files, let me know and I can modify.

### CODE REVIEW

**Comment by jdjuan** [comment]
This looks good to me. I will test it before tomorrow in case everybody else is busy. Thanks @dbfannin ! 🙂

**Comment by jvandemo** [comment]
@dbfannin &mdash; Looks great, thanks!

There should be no need for the `/` in `path.join(rootFolder, '/README.MD')`.

Can you please update it to `path.join(rootFolder, 'README.MD')`?

Thanks again!

**Comment by dbfannin** [comment]
Resolved conlicts and updated the path.join. @jvandemo, this should be good to go now. Thanks!

**Comment by jvandemo** [comment]
@dbfannin &mdash; Thank you for the rebase.

I think the `copy:readme` task is defined twice in `gulpfile.js`:

- [line 149](https://github.com/dbfannin/generator-angular2-library/blob/11cb0b41775f9858405edc081908193e85a10707/generators/app/templates/gulpfile.js#L149)
- [line 157](https://github.com/dbfannin/generator-angular2-library/blob/11cb0b41775f9858405edc081908193e85a10707/generators/app/templates/gulpfile.js#L157)

Can you fix that please?

Thanks again, David!

**Comment by dbfannin** [comment]
Well that's embarrassing. Not sure how I managed to do that. It should be good to go now (fingers crossed)

**Comment by jdjuan** [comment]
It looks good to me now 👍

**Comment by jvandemo** [comment]
Merged and released as v10.1.0.

@dbfannin &mdash; Thank you for your contribution! 👍 
@jdjuan &mdash; Thank you for your review 👍

**Pull request merged**
