### PR TITLE
feat(gulp): use gulp as a build tool

### PR DESCRIPTION
**Pull request by jvandemo**
This PR adds Gulp to support building libraries on Mac, Linux and Windows.

After generating a library, you should be able to build your library using:

```
$ npm run build
```

or use watch mode to build whenever a file changes in `src`:

```
$ npm run build:watch
```

It also adds support for inlining templates and styles, so external HTML templates and external CSS files can be used.

### CODE REVIEW

**Comment by caroso1222** [comment]
Wow this is huge thank you Jurgen! So excited about this. I was playing with this today and realized there's only one missing piece: sass build. I personally work with .scss files always. I added a sass build step in my gulpfile and then made a short modification in inline-resources to inline .css instead of .scss. That might be a feature request in the future so we better be prepared😬 I will show how I solved this (actually took a lot of things from angular-material) and then you decide whether to include it or not.

**Comment by jvandemo** [comment]
@caroso1222 &mdash; First of all, thank YOU for all your help. I really appreciate your efforts, much appreciated!

Once we get external confirmations that the generator is working as expected in different environments (Mac, Linux, Windows), we can create separate PR's for adding features such as support for Sass, Less, etc.

Ideally, the generator should be as lightweight and stable as possible in all environments.

There have been quite a bit of [issues with node-sass lately](https://github.com/sintaxi/harp/issues?utf8=%E2%9C%93&q=node-sass). I'm not sure if these issues would apply to this generator, but if they do, it may be wise for us to create a wiki page on how to include support for Sass, instead of adding the actual code.

It would be a bummer if the generator was prevented from evolving because some third party support like Sass or Less does not cooperate as expected.

What are your thoughts? Thanks!

**Comment by caroso1222** [comment]
Oh no, I'm only making a couple of PRs 😅 you're the one doing all the hard work, so thank you man! 

As for the sass issue, it's a super good idea to keep the generator as lightweight and stable as possible as you mention. So, if the sass thing will bring headaches in the future we better not even consider adding that, as you mention.

We can keep thinking about how to let users use these features, the wiki sounds good 🙂

**Comment by jvandemo** [comment]
@caroso1222 &mdash; Thank YOU for all your help, much appreciated 👍 

> As for the sass issue, it's a super good idea to keep the generator as lightweight and stable as possible as you mention. So, if the sass thing will bring headaches in the future we better not even consider adding that, as you mention.

Agree, we can gauge feature requests one by one to see if there is any value including them in the generator. There will be a lot of different scenarios for many different developers, so we won't be able to officially include or support them all.

Building a wiki with clear guidelines on how to add such feature (in case we don't include them in the generator) will indeed help people customize their own environment.

Thanks again!

**Pull request merged**
