### PR TITLE
Feat: support double quotes for templateUrl

### PR DESCRIPTION
**Pull request by tonysamperi**
* Fixed templateUrl regex to accept also double quotes.

### CODE REVIEW

**Comment by tonysamperi** [comment]
Closing due to some issue with gulp-nsp...
Will try to publish myself...

**Comment by jvandemo** [comment]
@tonysamperi &mdash; 👍

**Comment by tonysamperi** [comment]
@jvandemo it took a while, but it seems there were issues with package-lock.json.

I don't know if it all was caused by my node version 6.11.3

But now it works with everything above 4 (I chose v6, v8 and v10 in my travis config)

Hope this helps.

**Comment by jvandemo** [comment]
@tonysamperi &mdash; Great work, thank you! 🏆

**Comment by tonysamperi** [comment]
@jvandemo thanks to you!!
Pay attention at the README. I changed, since mine is also published on NPM so I don't know if yours works with the `yo generator-ng5-library` command.

**Comment by jvandemo** [comment]
@tonysamperi &mdash; Thank you for reporting. I've released v12.5.0 with an updated README and package.json. Thanks again for your contribution! 🏆

**Pull request merged**
